[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  # Add your Supabase environment variables here
  # VITE_SUPABASE_URL = "your_supabase_project_url"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"
  # SUPABASE_URL = "your_supabase_project_url"
  # SUPABASE_SERVICE_ROLE_KEY = "your_supabase_service_role_key"
  # FLUTTERWAVE_SECRET_KEY = "your_flutterwave_secret_key"

# Handle React Router - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle SPA routing
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/settings/*"
  to = "/index.html"
  status = 200
